vich_uploader:
    db_driver: orm

    mappings:
       users:
           uri_prefix: /pictures/users
           upload_destination: '%kernel.project_dir%/public/pictures/users'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
